before_script:
  - apt-get update -y && apt-get upgrade -y && apt-get install -y clang zlib1g-dev
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - . "$HOME/.cargo/env"
  - ruby -v
  - which ruby
  - bundle config --local build.zipruby "--with-cflags='-Wno-error=implicit-function-declaration -Wno-error=implicit-int -Wno-error=incompatible-function-pointer-types' --with-zlib-include=/usr/include"
  - dpkg -L zlib1g-dev
  - bundle install --jobs=$(nproc) --path=deps "${FLAGS[@]}"
  - bundle clean

test:
  image: ruby:$RUBY_VERSION
  script:
    - bundle exec rake test XML_BACKEND=REXML 2>/dev/null
    - bundle exec rake test XML_BACKEND=Oga 2>/dev/null
    - bundle exec rake test XML_BACKEND=Nokogiri 2>/dev/null
  except:
    - tags
  cache:
    key: ruby:$RUBY_VERSION
    paths:
      - deps
  parallel:
    matrix:
      - RUBY_VERSION: ["2.7", "3.0", "3.1", "3.2", "3.3", "3.4"]

pages:
  stage: deploy
  image: ruby:3.4
  dependencies:
    - test
  script:
    - bundle exec rake doc:yard
    - mv doc public
    - mv coverage public/
  artifacts:
    paths:
      - public
  only:
    - master
  cache:
    key: ruby:3.4
    paths:
      - deps
